apiVersion: v1
kind: Service
metadata:
  name: ibacc-master
spec:
  ports:
    - name: uilhttp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ibacc-master
  type: NodePort
  sessionAffinity: ClientIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ibacc-master
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ibacc-master
    spec:
      containers:
      - image: ecmcluster.icp:8500/default/ibacc-master:latest
        imagePullPolicy: Always
        name: ibacc-master
        command: ['/bin/bash']
        args: ['/entrypoint.sh', '/bin/bash']
        stdin: true
        tty: true
        resources:
          requests:
            cpu: 500m
        ports:
        - containerPort: 8080
          name: apihttp
        - containerPort: 80
          name: uihttp
        env:
          - name: LICENSE
            value: accept
          - name: mode
            value: CLI
          - name: SC_ECC_DEPLOY_ID
            value: ecm_staging_deploy
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: ibacc-cfg-volume
            mountPath: "/opt/ibm/ibacc"
      volumes:
        - name: ibacc-cfg-volume
          persistentVolumeClaim:
            claimName: ibacc-cfg-pvc 
      imagePullSecrets:
      - name: admin.registrykey
