apiVersion: v1
kind: Service
metadata:
  name: ecm-icn-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: icnserver-cluster1
  type: NodePort
  sessionAffinity: ClientIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ecm-icn
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: icnserver-cluster1
    spec:
      imagePullSecrets:
        - name: admin.registrykey
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - icnserver-cluster1
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: mycluster.icp:8500/default/navigator:latest
        imagePullPolicy: Always
        name: ecm-icn
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1024Mi
            cpu: 1
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        env:
          - name: LICENSE
            value: "Accept"
          - name: JVM_HEAP_XMS
            value: "512m"
          - name: JVM_HEAP_XMX
            value: "1024m"
          - name: TZ
            value: "Etc/UTC"
          - name: ICNDBTYPE
            value: "db2"
          - name: ICNJNDIDS
            value: "ECMClientDS"
          - name: ICNSCHEMA
            value: "ICNDB"
          - name: ICNTS
            value: "ICNDB"
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /navigator
            port: 9080
            httpHeaders:
              - name: Content-Encoding
                value: gzip
          initialDelaySeconds: 180
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /navigator
            port: 9080
            httpHeaders:
              - name: Content-Encoding
                value: gzip
          initialDelaySeconds: 600
          periodSeconds: 5
        volumeMounts:
          - name: icncfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides"  
            subPath: icn/configDropins/overrides
          - name: icnlogstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/logs"  
            subPath: icn/logs
          - name: icnpluginstore-pvc
            mountPath: "/opt/ibm/plugins"  
            subPath: plugins
          - name: icnvwcachestore-pvc
            mountPath: "/opt/ibm/viewerconfig/cache"  
            subPath: viewercache
          - name: icnvwlogstore-pvc
            mountPath: "/opt/ibm/viewerconfig/logs"  
            subPath: viewerlogs

      volumes:
        - name: icncfgstore-pvc 
          persistentVolumeClaim: 
            claimName: "icn-icp-cfgstore"
        - name: icnlogstore-pvc 
          persistentVolumeClaim: 
            claimName: "icn-icp-logstore"
        - name: icnpluginstore-pvc 
          persistentVolumeClaim: 
            claimName: "icn-icp-pluginstore"
        - name: icnvwcachestore-pvc 
          persistentVolumeClaim: 
            claimName: "icn-icp-vwcachestore"
        - name: icnvwlogstore-pvc 
          persistentVolumeClaim: 
            claimName: "icn-icp-vwlogstore"

